name: Deploy site with docs

on:
  push:
    branches:
      - main
      - test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Set env variable
        run: echo "GITHUB_TOKEN=${{ secrets.REPO_TOKEN }}" >> .env

      - name: Build the React app
        run: |
          CI=false npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          npm run deploy
