name: Deploy site with docs

on:
  push:
    branches:
      - main,
      - dev,
      - test

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set env varaibles
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
